version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    links:
      - zookeeper:zk
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zk:2181
      KAFKA_CREATE_TOPICS: "kafka-topic:3:1, second-kafka-topic:2:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper

  producer:
    image: maven:latest
    depends_on:
      - kafka
    links:
      - kafka
    volumes:
      - ${PROJECT_PATH}/springkafka-producer:${PROJECT_PATH}/springkafka-producer
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    ports:
      - "8080:8080"
    command: bash -c "cd ${PROJECT_PATH}/springkafka-producer && mvn spring-boot:run"
    
  consumer:
    image: maven:latest
    depends_on:
      - kafka
    links:
      - kafka
    volumes:
      - ${PROJECT_PATH}/springkafka-consumer:${PROJECT_PATH}/springkafka-consumer
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    command: bash -c "cd ${PROJECT_PATH}/springkafka-consumer && mvn spring-boot:run"